name: Auto Comment Issue

on:
  issues:
    types: [labeled]

jobs:
  auto-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Warn Bad Issue
        if: ${{ github.event.label.name == 'need improvement' }}
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            ğŸ“ To help us better understand and address your issue, please provide more information, or use the standard format, otherwise we will not process this issue.

            Reference document: 
            
              - [Creating an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/creating-an-issue)
              - [Basic writing and formatting syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)
            
            ---
            
            ğŸ“ ä¸ºäº†å¸®åŠ©æˆ‘ä»¬æ›´å¥½åœ°ç†è§£å’Œè§£å†³ä½ çš„é—®é¢˜ï¼Œè¯·æä¾›æ›´å¤šä¿¡æ¯ï¼Œæˆ–è€…ä½¿ç”¨è§„èŒƒçš„æ ¼å¼ï¼Œå¦åˆ™æˆ‘ä»¬ä¸ä¼šå¤„ç†è¿™ä¸ª issueã€‚

            å‚è€ƒæ–‡æ¡£ï¼š

              - [åˆ›å»ºè®®é¢˜](https://docs.github.com/zh/issues/tracking-your-work-with-issues/using-issues/creating-an-issue)
              - [åŸºæœ¬æ’°å†™å’Œæ ¼å¼è¯­æ³•](https://docs.github.com/zh/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)

      - name: Comment on Todos Issue
        if: ${{ github.event.label.name == 'todos' }}
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
           ğŸš€ This issue has been labeled as `todos` and added to our roadmap. We will prioritize it and provide updates as we make progress.

           ---

           ğŸš€ æ­¤ issue å·²è¢«æ ‡è®°ä¸º `todos` å¹¶è¢«åˆ—å…¥å¼€å‘è®¡åˆ’ä¸­ã€‚æˆ‘ä»¬å°†ä¼˜å…ˆå¤„ç†å®ƒï¼ŒåŒæ—¶ä¹Ÿä¼šå°†è¿›å±•åŒæ­¥åœ¨ä¸‹æ–¹ã€‚
